#!/bin/bash
# Shared entrypoint for the three OTS processes (opentakserver, eud_handler,
# cot_parser). Writes config.yml from environment variables on every boot so
# the .env file stays authoritative, then execs the requested process.
set -euo pipefail

DATA_DIR="${OTS_DATA_FOLDER:-/data/opentakserver}"
CONFIG_FILE="$DATA_DIR/config.yml"
NODE_ID_FILE="$DATA_DIR/.node_id"

require() {
    if [ -z "${!1:-}" ]; then
        echo "[skitak] ERROR: $1 must be set (see docker/.env.example)" >&2
        exit 1
    fi
}

require SECRET_KEY
require SECURITY_PASSWORD_SALT
require POSTGRES_PASSWORD

mkdir -p "$DATA_DIR"

# OTS_NODE_ID identifies this server in CoT traffic. It must be stable across
# restarts and identical for all three processes, so persist it once.
# The main opentakserver service boots first (the others depend_on its health),
# so there is no write race.
if [ ! -f "$NODE_ID_FILE" ]; then
    openssl rand -hex 16 > "$NODE_ID_FILE"
fi
NODE_ID="$(cat "$NODE_ID_FILE")"

# Uppercase keys — Flask only reads uppercase config values.
# Anything not set here keeps its opentakserver.defaultconfig default.
cat > "$CONFIG_FILE" <<EOF
# Generated by the SkiTAK entrypoint on every boot — do not edit manually,
# change docker/.env instead.
DEBUG: ${OTS_DEBUG:-false}
SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://${POSTGRES_USER:-skitak}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}/${POSTGRES_DB:-skitak}"
SECRET_KEY: "${SECRET_KEY}"
SECURITY_PASSWORD_SALT: "${SECURITY_PASSWORD_SALT}"
OTS_NODE_ID: "${NODE_ID}"
OTS_LISTENER_ADDRESS: "0.0.0.0"
OTS_LISTENER_PORT: 8081
OTS_RABBITMQ_SERVER_ADDRESS: "${RABBITMQ_HOST:-rabbitmq}"
OTS_RABBITMQ_USERNAME: "guest"
OTS_RABBITMQ_PASSWORD: "guest"
OTS_ENABLE_TCP_STREAMING_PORT: false
OTS_ENABLE_MUMBLE_AUTHENTICATION: false
OTS_MEDIAMTX_ENABLE: false
OTS_ENABLE_PLUGINS: true
EOF

echo "[skitak] Wrote $CONFIG_FILE — starting: $*"
exec "$@"
