#!/bin/bash
set -e

DATA_DIR="/data/opentakserver"
CONFIG_FILE="$DATA_DIR/config.yml"
FIRST_BOOT_FLAG="$DATA_DIR/.initialized"

# ── Write OTS config from environment ─────────────────────────────────────
mkdir -p "$DATA_DIR/certs" "$DATA_DIR/uploads" "$DATA_DIR/logs"

cat > "$CONFIG_FILE" <<EOF
# Generated by SkiTAK entrypoint — do not edit manually
database_uri: "${OTS_DATABASE_URI}"
secret_key: "${OTS_SECRET_KEY}"
server_address: "${OTS_SERVER_ADDRESS}"
data_dir: "${DATA_DIR}"

rabbitmq:
  host: "${OTS_RABBITMQ_HOST:-rabbitmq}"
  port: ${OTS_RABBITMQ_PORT:-5672}
  user: "${OTS_RABBITMQ_USER}"
  password: "${OTS_RABBITMQ_PASS}"

ssl:
  enabled: true
  cert_dir: "${DATA_DIR}/certs"

ports:
  tcp_cot: 8088
  ssl_cot: 8089
  api: 8080

mumble:
  enabled: ${OTS_ENABLE_MUMBLE_AUTH:-false}
  host: "${OTS_MUMBLE_HOST:-mumble}"
  port: ${OTS_MUMBLE_PORT:-6502}

logging:
  level: "${OTS_LOG_LEVEL:-INFO}"
EOF

# ── First boot: initialise CA and admin user ──────────────────────────────
if [ ! -f "$FIRST_BOOT_FLAG" ]; then
    echo "[skitak] First boot — initialising..."

    # OTS generates its own CA and server certs on first run
    opentakserver --init --config "$CONFIG_FILE"

    # Create initial admin account
    opentakserver --create-admin \
        --username "${OTS_ADMIN_USER:-admin}" \
        --password "${OTS_ADMIN_PASSWORD}" \
        --config "$CONFIG_FILE"

    touch "$FIRST_BOOT_FLAG"
    echo "[skitak] Initialisation complete."
fi

# ── Start OTS ─────────────────────────────────────────────────────────────
echo "[skitak] Starting OpenTAKServer..."
exec opentakserver --config "$CONFIG_FILE"
